version: "3.9"

services:
  euphire:
    build: .
    container_name: euphire
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - BOT_TOKEN
      - CLIENT_ID
    networks:
      - euphire-network

networks:
  euphire-network:
    driver: bridge
